// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SafeFutureInventorySystem.Data;

#nullable disable

namespace SafeFutureInventorySystem.Migrations.InventoryMigrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("SafeFutureInventorySystem.Models.DonationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DonationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DonorName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityDonated")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.ToTable("DonationLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DonationDate = new DateTime(2025, 12, 29, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5127),
                            DonorName = "Sarah Johnson",
                            InventoryItemId = 1,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 15
                        },
                        new
                        {
                            Id = 2,
                            DonationDate = new DateTime(2026, 1, 28, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5447),
                            DonorName = "Michael Chen",
                            InventoryItemId = 2,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 8
                        },
                        new
                        {
                            Id = 3,
                            DonationDate = new DateTime(2025, 11, 29, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5470),
                            DonorName = "Jennifer Martinez",
                            InventoryItemId = 3,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 3
                        },
                        new
                        {
                            Id = 4,
                            DonationDate = new DateTime(2026, 2, 27, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5472),
                            DonorName = "Robert Williams",
                            InventoryItemId = 4,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 45
                        },
                        new
                        {
                            Id = 5,
                            DonationDate = new DateTime(2026, 3, 19, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5476),
                            DonorName = "Lisa Anderson",
                            InventoryItemId = 5,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 180
                        },
                        new
                        {
                            Id = 6,
                            DonationDate = new DateTime(2026, 3, 9, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5478),
                            DonorName = "Target Store #1234",
                            InventoryItemId = 6,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 22
                        },
                        new
                        {
                            Id = 7,
                            DonationDate = new DateTime(2026, 3, 24, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5480),
                            DonorName = "David Thompson",
                            InventoryItemId = 7,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 130
                        },
                        new
                        {
                            Id = 8,
                            DonationDate = new DateTime(2026, 4, 10, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5481),
                            DonorName = "Emily Davis",
                            InventoryItemId = 8,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 250
                        },
                        new
                        {
                            Id = 9,
                            DonationDate = new DateTime(2026, 3, 14, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5483),
                            DonorName = "James Wilson",
                            InventoryItemId = 9,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 68
                        },
                        new
                        {
                            Id = 10,
                            DonationDate = new DateTime(2026, 3, 29, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5485),
                            DonorName = "Patricia Moore",
                            InventoryItemId = 10,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 60
                        },
                        new
                        {
                            Id = 11,
                            DonationDate = new DateTime(2026, 4, 10, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5487),
                            DonorName = "Walmart Store #5678",
                            InventoryItemId = 10,
                            Notes = "Merged into existing stock. Previous qty: 60",
                            QuantityDonated = 50
                        },
                        new
                        {
                            Id = 12,
                            DonationDate = new DateTime(2026, 4, 21, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5488),
                            DonorName = "St. Mary's Church",
                            InventoryItemId = 10,
                            Notes = "Merged into existing stock. Previous qty: 110",
                            QuantityDonated = 40
                        },
                        new
                        {
                            Id = 13,
                            DonationDate = new DateTime(2026, 4, 3, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5490),
                            DonorName = "Christopher Taylor",
                            InventoryItemId = 11,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 80
                        },
                        new
                        {
                            Id = 14,
                            DonationDate = new DateTime(2026, 4, 14, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5491),
                            DonorName = "Jessica Brown",
                            InventoryItemId = 11,
                            Notes = "Merged into existing stock. Previous qty: 80",
                            QuantityDonated = 70
                        },
                        new
                        {
                            Id = 15,
                            DonationDate = new DateTime(2026, 4, 25, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5493),
                            DonorName = "Community Health Center",
                            InventoryItemId = 11,
                            Notes = "Merged into existing stock. Previous qty: 150",
                            QuantityDonated = 50
                        },
                        new
                        {
                            Id = 16,
                            DonationDate = new DateTime(2026, 4, 8, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5495),
                            DonorName = "Daniel Garcia",
                            InventoryItemId = 12,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 180
                        },
                        new
                        {
                            Id = 17,
                            DonationDate = new DateTime(2026, 4, 13, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5496),
                            DonorName = "Matthew Rodriguez",
                            InventoryItemId = 13,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 165
                        },
                        new
                        {
                            Id = 18,
                            DonationDate = new DateTime(2026, 4, 18, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5498),
                            DonorName = "Ashley Lewis",
                            InventoryItemId = 14,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 140
                        },
                        new
                        {
                            Id = 19,
                            DonationDate = new DateTime(2026, 4, 20, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5508),
                            DonorName = "Hannah Campbell",
                            InventoryItemId = 15,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 120
                        },
                        new
                        {
                            Id = 20,
                            DonationDate = new DateTime(2026, 4, 23, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5509),
                            DonorName = "Nathan Parker",
                            InventoryItemId = 16,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 95
                        },
                        new
                        {
                            Id = 21,
                            DonationDate = new DateTime(2026, 3, 31, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5511),
                            DonorName = "Alexis Evans",
                            InventoryItemId = 17,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 100
                        },
                        new
                        {
                            Id = 22,
                            DonationDate = new DateTime(2026, 4, 18, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5513),
                            DonorName = "Samuel Edwards",
                            InventoryItemId = 17,
                            Notes = "Merged into existing stock. Previous qty: 100",
                            QuantityDonated = 45
                        },
                        new
                        {
                            Id = 23,
                            DonationDate = new DateTime(2026, 4, 6, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5514),
                            DonorName = "Joshua Walker",
                            InventoryItemId = 18,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 100
                        },
                        new
                        {
                            Id = 24,
                            DonationDate = new DateTime(2026, 4, 16, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5516),
                            DonorName = "Grace Collins",
                            InventoryItemId = 18,
                            Notes = "Merged into existing stock. Previous qty: 100",
                            QuantityDonated = 80
                        },
                        new
                        {
                            Id = 25,
                            DonationDate = new DateTime(2026, 4, 24, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5518),
                            DonorName = "Benjamin Stewart",
                            InventoryItemId = 18,
                            Notes = "Merged into existing stock. Previous qty: 180",
                            QuantityDonated = 40
                        },
                        new
                        {
                            Id = 26,
                            DonationDate = new DateTime(2026, 4, 14, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5519),
                            DonorName = "Amanda Hall",
                            InventoryItemId = 19,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 85
                        },
                        new
                        {
                            Id = 27,
                            DonationDate = new DateTime(2026, 4, 11, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5521),
                            DonorName = "Community Health Center",
                            InventoryItemId = 20,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 135
                        },
                        new
                        {
                            Id = 28,
                            DonationDate = new DateTime(2026, 4, 17, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5522),
                            DonorName = "Ryan Allen",
                            InventoryItemId = 21,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 70
                        },
                        new
                        {
                            Id = 29,
                            DonationDate = new DateTime(2026, 4, 12, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5524),
                            DonorName = "Samantha Young",
                            InventoryItemId = 22,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 125
                        },
                        new
                        {
                            Id = 30,
                            DonationDate = new DateTime(2026, 4, 19, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5526),
                            DonorName = "Brandon King",
                            InventoryItemId = 23,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 90
                        },
                        new
                        {
                            Id = 31,
                            DonationDate = new DateTime(2026, 4, 7, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5527),
                            DonorName = "Nicole Wright",
                            InventoryItemId = 24,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 100
                        },
                        new
                        {
                            Id = 32,
                            DonationDate = new DateTime(2026, 4, 19, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5529),
                            DonorName = "Justin Scott",
                            InventoryItemId = 24,
                            Notes = "Merged into existing stock. Previous qty: 100",
                            QuantityDonated = 60
                        },
                        new
                        {
                            Id = 33,
                            DonationDate = new DateTime(2026, 4, 15, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5530),
                            DonorName = "Megan Green",
                            InventoryItemId = 25,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 105
                        },
                        new
                        {
                            Id = 34,
                            DonationDate = new DateTime(2026, 4, 22, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5532),
                            DonorName = "Tyler Adams",
                            InventoryItemId = 26,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 200
                        },
                        new
                        {
                            Id = 35,
                            DonationDate = new DateTime(2026, 4, 4, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5541),
                            DonorName = "Rachel Baker",
                            InventoryItemId = 27,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 80
                        },
                        new
                        {
                            Id = 36,
                            DonationDate = new DateTime(2026, 4, 21, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5543),
                            DonorName = "Kevin Nelson",
                            InventoryItemId = 28,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 65
                        },
                        new
                        {
                            Id = 37,
                            DonationDate = new DateTime(2026, 4, 24, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5544),
                            DonorName = "Lauren Carter",
                            InventoryItemId = 29,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 55
                        },
                        new
                        {
                            Id = 38,
                            DonationDate = new DateTime(2026, 4, 1, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5546),
                            DonorName = "Jacob Mitchell",
                            InventoryItemId = 30,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 45
                        },
                        new
                        {
                            Id = 39,
                            DonationDate = new DateTime(2026, 4, 2, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5548),
                            DonorName = "Kimberly Perez",
                            InventoryItemId = 31,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 100
                        },
                        new
                        {
                            Id = 40,
                            DonationDate = new DateTime(2026, 4, 13, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5549),
                            DonorName = "Austin Roberts",
                            InventoryItemId = 32,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 75
                        },
                        new
                        {
                            Id = 41,
                            DonationDate = new DateTime(2026, 4, 16, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5551),
                            DonorName = "Brittany Turner",
                            InventoryItemId = 33,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 88
                        },
                        new
                        {
                            Id = 42,
                            DonationDate = new DateTime(2026, 3, 30, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5552),
                            DonorName = "Costco Wholesale",
                            InventoryItemId = 34,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 150
                        },
                        new
                        {
                            Id = 43,
                            DonationDate = new DateTime(2026, 3, 28, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5554),
                            DonorName = "Zachary Phillips",
                            InventoryItemId = 35,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 35
                        },
                        new
                        {
                            Id = 44,
                            DonationDate = new DateTime(2026, 3, 26, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5556),
                            DonorName = "Victoria Sanchez",
                            InventoryItemId = 36,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 50
                        },
                        new
                        {
                            Id = 45,
                            DonationDate = new DateTime(2026, 4, 16, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5557),
                            DonorName = "Alexander Morris",
                            InventoryItemId = 37,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 75
                        },
                        new
                        {
                            Id = 46,
                            DonationDate = new DateTime(2026, 4, 9, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5559),
                            DonorName = "Sophia Rogers",
                            InventoryItemId = 38,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 110
                        },
                        new
                        {
                            Id = 47,
                            DonationDate = new DateTime(2026, 4, 5, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5560),
                            DonorName = "Elijah Reed",
                            InventoryItemId = 39,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 115
                        },
                        new
                        {
                            Id = 48,
                            DonationDate = new DateTime(2026, 4, 20, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5562),
                            DonorName = "Olivia Cook",
                            InventoryItemId = 40,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 140
                        },
                        new
                        {
                            Id = 49,
                            DonationDate = new DateTime(2026, 3, 17, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5563),
                            DonorName = "Mason Morgan",
                            InventoryItemId = 41,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 92
                        },
                        new
                        {
                            Id = 50,
                            DonationDate = new DateTime(2026, 3, 4, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5572),
                            DonorName = "Ava Bell",
                            InventoryItemId = 42,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 100
                        },
                        new
                        {
                            Id = 51,
                            DonationDate = new DateTime(2026, 4, 6, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5574),
                            DonorName = "Lucas Murphy",
                            InventoryItemId = 42,
                            Notes = "Merged into existing stock. Previous qty: 100",
                            QuantityDonated = 85
                        },
                        new
                        {
                            Id = 52,
                            DonationDate = new DateTime(2026, 3, 11, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5576),
                            DonorName = "Isabella Bailey",
                            InventoryItemId = 43,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 167
                        },
                        new
                        {
                            Id = 53,
                            DonationDate = new DateTime(2026, 3, 21, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5577),
                            DonorName = "Ethan Rivera",
                            InventoryItemId = 44,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 78
                        },
                        new
                        {
                            Id = 54,
                            DonationDate = new DateTime(2026, 3, 7, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5579),
                            DonorName = "Mia Cooper",
                            InventoryItemId = 45,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 61
                        },
                        new
                        {
                            Id = 55,
                            DonationDate = new DateTime(2026, 3, 15, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5581),
                            DonorName = "Charlotte Cox",
                            InventoryItemId = 46,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 103
                        },
                        new
                        {
                            Id = 56,
                            DonationDate = new DateTime(2026, 2, 22, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5582),
                            DonorName = "Aiden Howard",
                            InventoryItemId = 47,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 47
                        },
                        new
                        {
                            Id = 57,
                            DonationDate = new DateTime(2026, 2, 16, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5584),
                            DonorName = "Amelia Ward",
                            InventoryItemId = 48,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 82
                        },
                        new
                        {
                            Id = 58,
                            DonationDate = new DateTime(2026, 1, 30, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5585),
                            DonorName = "Liam Torres",
                            InventoryItemId = 49,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 18
                        },
                        new
                        {
                            Id = 59,
                            DonationDate = new DateTime(2026, 2, 10, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5587),
                            DonorName = "Harper Peterson",
                            InventoryItemId = 50,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 100
                        },
                        new
                        {
                            Id = 60,
                            DonationDate = new DateTime(2026, 3, 19, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5588),
                            DonorName = "Noah Gray",
                            InventoryItemId = 50,
                            Notes = "Merged into existing stock. Previous qty: 100",
                            QuantityDonated = 84
                        },
                        new
                        {
                            Id = 61,
                            DonationDate = new DateTime(2026, 4, 18, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5590),
                            DonorName = "Costco Wholesale",
                            InventoryItemId = 50,
                            Notes = "Merged into existing stock. Previous qty: 184",
                            QuantityDonated = 50
                        },
                        new
                        {
                            Id = 62,
                            DonationDate = new DateTime(2026, 1, 23, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5592),
                            DonorName = "Patricia Moore",
                            InventoryItemId = 51,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 12
                        },
                        new
                        {
                            Id = 63,
                            DonationDate = new DateTime(2026, 1, 16, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5593),
                            DonorName = "Ryan Allen",
                            InventoryItemId = 52,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 28
                        },
                        new
                        {
                            Id = 64,
                            DonationDate = new DateTime(2026, 3, 1, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5595),
                            DonorName = "Lisa Anderson",
                            InventoryItemId = 53,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 144
                        },
                        new
                        {
                            Id = 65,
                            DonationDate = new DateTime(2026, 2, 4, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5596),
                            DonorName = "Logan Richardson",
                            InventoryItemId = 54,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 12
                        },
                        new
                        {
                            Id = 66,
                            DonationDate = new DateTime(2026, 3, 28, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5599),
                            DonorName = "James Wilson",
                            InventoryItemId = 54,
                            Notes = "Merged into existing stock. Previous qty: 12",
                            QuantityDonated = 10
                        },
                        new
                        {
                            Id = 67,
                            DonationDate = new DateTime(2026, 2, 18, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5600),
                            DonorName = "Samantha Young",
                            InventoryItemId = 55,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 67
                        },
                        new
                        {
                            Id = 68,
                            DonationDate = new DateTime(2026, 3, 13, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5602),
                            DonorName = "Brandon King",
                            InventoryItemId = 56,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 98
                        },
                        new
                        {
                            Id = 69,
                            DonationDate = new DateTime(2026, 1, 8, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5604),
                            DonorName = "Emily Davis",
                            InventoryItemId = 57,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 15
                        },
                        new
                        {
                            Id = 70,
                            DonationDate = new DateTime(2026, 1, 20, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5605),
                            DonorName = "David Thompson",
                            InventoryItemId = 58,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 31
                        },
                        new
                        {
                            Id = 71,
                            DonationDate = new DateTime(2026, 2, 25, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5607),
                            DonorName = "Target Store #1234",
                            InventoryItemId = 59,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 176
                        },
                        new
                        {
                            Id = 72,
                            DonationDate = new DateTime(2026, 2, 12, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(5608),
                            DonorName = "Noah Gray",
                            InventoryItemId = 60,
                            Notes = "Initial donation — item created.",
                            QuantityDonated = 54
                        });
                });

            modelBuilder.Entity("SafeFutureInventorySystem.Models.InventoryAdjustmentLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdjustedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AdjustmentDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OldQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.ToTable("AdjustmentLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdjustedBy = "Admin",
                            AdjustmentDate = new DateTime(2026, 4, 23, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(6270),
                            InventoryItemId = 10,
                            NewQuantity = 150,
                            OldQuantity = 120,
                            Reason = "New shipment received"
                        },
                        new
                        {
                            Id = 2,
                            AdjustedBy = "Volunteer",
                            AdjustmentDate = new DateTime(2026, 4, 26, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(6440),
                            InventoryItemId = 10,
                            NewQuantity = 130,
                            OldQuantity = 150,
                            Reason = "Distributed to families"
                        },
                        new
                        {
                            Id = 3,
                            AdjustedBy = "Admin",
                            AdjustmentDate = new DateTime(2026, 4, 25, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(6442),
                            InventoryItemId = 18,
                            NewQuantity = 220,
                            OldQuantity = 250,
                            Reason = "Used for community event"
                        });
                });

            modelBuilder.Entity("SafeFutureInventorySystem.Models.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("LowStockThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("InventoryItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "070074680002",
                            Category = "Baby Formula",
                            DateAdded = new DateTime(2025, 12, 29, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(491),
                            Description = "EXPIRED - Similac Advance, 12.4 oz",
                            ExpirationDate = new DateTime(2026, 3, 29, 16, 41, 52, 305, DateTimeKind.Local).AddTicks(5506),
                            LowStockThreshold = 0,
                            Name = "Expired Baby Formula",
                            Quantity = 15
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "036000516517",
                            Category = "Baby Wipes",
                            DateAdded = new DateTime(2026, 1, 28, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(861),
                            Description = "EXPIRED - Huggies Natural Care, 72 count",
                            ExpirationDate = new DateTime(2026, 4, 13, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(857),
                            LowStockThreshold = 0,
                            Name = "Expired Baby Wipes",
                            Quantity = 8
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "085898800015",
                            Category = "Baby Care",
                            DateAdded = new DateTime(2025, 11, 29, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(880),
                            Description = "EXPIRED - Boudreaux's Butt Paste, 4 oz",
                            ExpirationDate = new DateTime(2026, 2, 27, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(865),
                            LowStockThreshold = 0,
                            Name = "Expired Diaper Cream",
                            Quantity = 3
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "050000339877",
                            Category = "Baby Formula",
                            DateAdded = new DateTime(2026, 2, 27, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(886),
                            Description = "EXPIRING SOON - Gentle powder, 32 oz",
                            ExpirationDate = new DateTime(2026, 5, 1, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(884),
                            LowStockThreshold = 0,
                            Name = "Gerber Good Start Formula",
                            Quantity = 45
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "859668006010",
                            Category = "Baby Wipes",
                            DateAdded = new DateTime(2026, 3, 19, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(889),
                            Description = "EXPIRING SOON - 99.9% water, 540 count",
                            ExpirationDate = new DateTime(2026, 5, 3, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(888),
                            LowStockThreshold = 0,
                            Name = "WaterWipes Baby Wipes",
                            Quantity = 180
                        },
                        new
                        {
                            Id = 6,
                            Barcode = "051000138255",
                            Category = "Baby Food",
                            DateAdded = new DateTime(2026, 3, 9, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(891),
                            Description = "EXPIRING SOON - Stage 1, 4 oz jar",
                            ExpirationDate = new DateTime(2026, 5, 5, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(890),
                            LowStockThreshold = 0,
                            Name = "Organic Baby Food - Peas",
                            Quantity = 22
                        },
                        new
                        {
                            Id = 7,
                            Barcode = "070074682532",
                            Category = "Baby Formula",
                            DateAdded = new DateTime(2026, 3, 24, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(895),
                            Description = "Expiring this month - 30.8 oz powder",
                            ExpirationDate = new DateTime(2026, 5, 23, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(893),
                            LowStockThreshold = 0,
                            Name = "Similac Pro-Advance Formula",
                            Quantity = 130
                        },
                        new
                        {
                            Id = 8,
                            Barcode = "037000830689",
                            Category = "Baby Wipes",
                            DateAdded = new DateTime(2026, 4, 10, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(898),
                            Description = "Expiring this month - 504 count",
                            ExpirationDate = new DateTime(2026, 5, 18, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(897),
                            LowStockThreshold = 0,
                            Name = "Pampers Sensitive Wipes",
                            Quantity = 250
                        },
                        new
                        {
                            Id = 9,
                            Barcode = "363824009001",
                            Category = "Baby Health",
                            DateAdded = new DateTime(2026, 3, 14, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(900),
                            Description = "Expiring this month - Liquid supplement",
                            ExpirationDate = new DateTime(2026, 5, 26, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(899),
                            LowStockThreshold = 0,
                            Name = "Baby Vitamin D Drops",
                            Quantity = 68
                        },
                        new
                        {
                            Id = 10,
                            Barcode = "037000465911",
                            Category = "Diapers",
                            DateAdded = new DateTime(2026, 3, 29, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(919),
                            Description = "Size N, Up to 10 lbs, 32 count pack",
                            ExpirationDate = new DateTime(2027, 10, 28, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(902),
                            LowStockThreshold = 0,
                            Name = "Pampers Newborn Diapers",
                            Quantity = 150
                        },
                        new
                        {
                            Id = 11,
                            Barcode = "036000406481",
                            Category = "Diapers",
                            DateAdded = new DateTime(2026, 4, 3, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(923),
                            Description = "Size 1, 8-14 lbs, 84 count pack",
                            ExpirationDate = new DateTime(2028, 4, 28, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(921),
                            LowStockThreshold = 0,
                            Name = "Huggies Size 1 Diapers",
                            Quantity = 200
                        },
                        new
                        {
                            Id = 12,
                            Barcode = "037000465928",
                            Category = "Diapers",
                            DateAdded = new DateTime(2026, 4, 8, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(926),
                            Description = "Size 2, 12-18 lbs, 112 count pack",
                            ExpirationDate = new DateTime(2027, 12, 28, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(925),
                            LowStockThreshold = 0,
                            Name = "Pampers Size 2 Diapers",
                            Quantity = 180
                        },
                        new
                        {
                            Id = 13,
                            Barcode = "036000406498",
                            Category = "Diapers",
                            DateAdded = new DateTime(2026, 4, 13, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(937),
                            Description = "Size 3, 16-28 lbs, 104 count pack",
                            ExpirationDate = new DateTime(2028, 2, 28, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(928),
                            LowStockThreshold = 0,
                            Name = "Huggies Size 3 Diapers",
                            Quantity = 165
                        },
                        new
                        {
                            Id = 14,
                            Barcode = "037000465935",
                            Category = "Diapers",
                            DateAdded = new DateTime(2026, 4, 18, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(941),
                            Description = "Size 4, 22-37 lbs, 92 count pack",
                            ExpirationDate = new DateTime(2027, 11, 28, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(940),
                            LowStockThreshold = 0,
                            Name = "Pampers Size 4 Diapers",
                            Quantity = 140
                        },
                        new
                        {
                            Id = 15,
                            Barcode = "036000406504",
                            Category = "Diapers",
                            DateAdded = new DateTime(2026, 4, 20, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(944),
                            Description = "Size 5, 27+ lbs, 80 count pack",
                            ExpirationDate = new DateTime(2028, 1, 28, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(943),
                            LowStockThreshold = 0,
                            Name = "Huggies Size 5 Diapers",
                            Quantity = 120
                        },
                        new
                        {
                            Id = 16,
                            Barcode = "037000465942",
                            Category = "Diapers",
                            DateAdded = new DateTime(2026, 4, 23, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(947),
                            Description = "Size 6, 35+ lbs, 68 count pack",
                            ExpirationDate = new DateTime(2028, 3, 28, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(946),
                            LowStockThreshold = 0,
                            Name = "Pampers Size 6 Diapers",
                            Quantity = 95
                        },
                        new
                        {
                            Id = 17,
                            Barcode = "300871214415",
                            Category = "Baby Formula",
                            DateAdded = new DateTime(2026, 3, 31, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(950),
                            Description = "Infant formula powder, 28.3 oz",
                            ExpirationDate = new DateTime(2027, 2, 28, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(949),
                            LowStockThreshold = 0,
                            Name = "Enfamil NeuroPro Formula",
                            Quantity = 145
                        },
                        new
                        {
                            Id = 18,
                            Barcode = "036000516500",
                            Category = "Baby Wipes",
                            DateAdded = new DateTime(2026, 4, 6, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(953),
                            Description = "Fragrance-free, 552 count (8 packs)",
                            ExpirationDate = new DateTime(2027, 6, 28, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(952),
                            LowStockThreshold = 0,
                            Name = "Huggies Natural Care Wipes",
                            Quantity = 220
                        },
                        new
                        {
                            Id = 19,
                            Barcode = "067981105001",
                            Category = "Diapering",
                            DateAdded = new DateTime(2026, 4, 14, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(956),
                            Description = "Desitin Maximum Strength, 4 oz tube",
                            ExpirationDate = new DateTime(2027, 10, 28, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(955),
                            LowStockThreshold = 0,
                            Name = "Diaper Rash Cream",
                            Quantity = 85
                        },
                        new
                        {
                            Id = 20,
                            Barcode = "381371161423",
                            Category = "Baby Care",
                            DateAdded = new DateTime(2026, 4, 11, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(959),
                            Description = "Johnson's Head-to-Toe, 27.1 fl oz",
                            ExpirationDate = new DateTime(2028, 10, 28, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(958),
                            LowStockThreshold = 0,
                            Name = "Baby Shampoo & Body Wash",
                            Quantity = 135
                        },
                        new
                        {
                            Id = 21,
                            Barcode = "072239311004",
                            Category = "Feeding",
                            DateAdded = new DateTime(2026, 4, 17, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(961),
                            Description = "Dr. Brown's Anti-Colic, 3-pack",
                            LowStockThreshold = 0,
                            Name = "Baby Bottles 8oz",
                            Quantity = 70
                        },
                        new
                        {
                            Id = 22,
                            Barcode = "072239314012",
                            Category = "Feeding",
                            DateAdded = new DateTime(2026, 4, 12, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(962),
                            Description = "Silicone, 6-pack, 0-3 months",
                            LowStockThreshold = 0,
                            Name = "Bottle Nipples - Slow Flow",
                            Quantity = 125
                        },
                        new
                        {
                            Id = 23,
                            Barcode = "849854012345",
                            Category = "Feeding",
                            DateAdded = new DateTime(2026, 4, 19, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(964),
                            Description = "100% cotton, 10-pack set",
                            LowStockThreshold = 0,
                            Name = "Burp Cloths",
                            Quantity = 90
                        },
                        new
                        {
                            Id = 24,
                            Barcode = "078742317298",
                            Category = "Clothing",
                            DateAdded = new DateTime(2026, 4, 7, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(983),
                            Description = "Short sleeve, 5-pack, assorted colors",
                            LowStockThreshold = 0,
                            Name = "Onesies 0-3 Months",
                            Quantity = 160
                        },
                        new
                        {
                            Id = 25,
                            Barcode = "078742317305",
                            Category = "Clothing",
                            DateAdded = new DateTime(2026, 4, 15, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(985),
                            Description = "Footed sleepers, fleece, 3-pack",
                            LowStockThreshold = 0,
                            Name = "Baby Sleepers 3-6 Months",
                            Quantity = 105
                        },
                        new
                        {
                            Id = 26,
                            Barcode = "849854023456",
                            Category = "Clothing",
                            DateAdded = new DateTime(2026, 4, 22, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(987),
                            Description = "Non-slip grip, 12-pack",
                            LowStockThreshold = 0,
                            Name = "Baby Socks 0-12 Months",
                            Quantity = 200
                        },
                        new
                        {
                            Id = 27,
                            Barcode = "849854034567",
                            Category = "Clothing",
                            DateAdded = new DateTime(2026, 4, 4, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(989),
                            Description = "Scratch-free mittens, 6-pack",
                            LowStockThreshold = 0,
                            Name = "Baby Mittens",
                            Quantity = 80
                        },
                        new
                        {
                            Id = 28,
                            Barcode = "735363012010",
                            Category = "Diapering",
                            DateAdded = new DateTime(2026, 4, 21, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(991),
                            Description = "Waterproof, 50 count pack",
                            LowStockThreshold = 0,
                            Name = "Disposable Changing Pads",
                            Quantity = 65
                        },
                        new
                        {
                            Id = 29,
                            Barcode = "849854045678",
                            Category = "Baby Care",
                            DateAdded = new DateTime(2026, 4, 24, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(993),
                            Description = "Safety nail care set with file",
                            LowStockThreshold = 0,
                            Name = "Baby Nail Clippers",
                            Quantity = 55
                        },
                        new
                        {
                            Id = 30,
                            Barcode = "853689006133",
                            Category = "Baby Health",
                            DateAdded = new DateTime(2026, 4, 1, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(994),
                            Description = "NoseFrida with 20 filters",
                            LowStockThreshold = 0,
                            Name = "Nasal Aspirator",
                            Quantity = 45
                        },
                        new
                        {
                            Id = 31,
                            Barcode = "849854056789",
                            Category = "Bedding",
                            DateAdded = new DateTime(2026, 4, 2, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(996),
                            Description = "Muslin, 4-pack, 47x47 inches",
                            LowStockThreshold = 0,
                            Name = "Swaddle Blankets",
                            Quantity = 100
                        },
                        new
                        {
                            Id = 32,
                            Barcode = "849854067890",
                            Category = "Bedding",
                            DateAdded = new DateTime(2026, 4, 13, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(998),
                            Description = "Fitted, 100% cotton, 2-pack",
                            LowStockThreshold = 0,
                            Name = "Crib Sheets",
                            Quantity = 75
                        },
                        new
                        {
                            Id = 33,
                            Barcode = "849854078901",
                            Category = "Bathing",
                            DateAdded = new DateTime(2026, 4, 16, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(1000),
                            Description = "Extra soft, 30x30 inches, 3-pack",
                            LowStockThreshold = 0,
                            Name = "Baby Hooded Towels",
                            Quantity = 88
                        },
                        new
                        {
                            Id = 34,
                            Barcode = "849854089012",
                            Category = "Bathing",
                            DateAdded = new DateTime(2026, 3, 30, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(1001),
                            Description = "Ultra-soft, 12-pack",
                            LowStockThreshold = 0,
                            Name = "Baby Washcloths",
                            Quantity = 150
                        },
                        new
                        {
                            Id = 35,
                            Barcode = "849854090123",
                            Category = "Accessories",
                            DateAdded = new DateTime(2026, 3, 28, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(1003),
                            Description = "Multi-pocket backpack style",
                            LowStockThreshold = 0,
                            Name = "Diaper Bags",
                            Quantity = 35
                        },
                        new
                        {
                            Id = 36,
                            Barcode = "849854101234",
                            Category = "Baby Health",
                            DateAdded = new DateTime(2026, 3, 26, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(1005),
                            Description = "Digital forehead & ear thermometer",
                            LowStockThreshold = 0,
                            Name = "Baby Thermometer",
                            Quantity = 50
                        },
                        new
                        {
                            Id = 37,
                            Barcode = "732913441914",
                            Category = "Diapers",
                            DateAdded = new DateTime(2026, 4, 16, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(1008),
                            Description = "Eco-friendly, Size 1, 8-14 lbs, 40 count",
                            ExpirationDate = new DateTime(2027, 7, 28, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(1007),
                            LowStockThreshold = 0,
                            Name = "Seventh Generation Size 1 Diapers",
                            Quantity = 75
                        },
                        new
                        {
                            Id = 38,
                            Barcode = "381371161416",
                            Category = "Baby Care",
                            DateAdded = new DateTime(2026, 4, 9, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(1018),
                            Description = "Johnson's Baby Powder, cornstarch, 9 oz",
                            ExpirationDate = new DateTime(2028, 4, 28, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(1017),
                            LowStockThreshold = 0,
                            Name = "Baby Powder",
                            Quantity = 110
                        },
                        new
                        {
                            Id = 39,
                            Barcode = "381371161430",
                            Category = "Baby Care",
                            DateAdded = new DateTime(2026, 4, 5, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(1022),
                            Description = "Aveeno Baby Daily Moisture, 18 fl oz",
                            ExpirationDate = new DateTime(2028, 6, 28, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(1020),
                            LowStockThreshold = 0,
                            Name = "Baby Lotion",
                            Quantity = 115
                        },
                        new
                        {
                            Id = 40,
                            Barcode = "072239314029",
                            Category = "Comfort",
                            DateAdded = new DateTime(2026, 4, 20, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(1024),
                            Description = "Orthodontic, BPA-free, 4-pack",
                            ExpirationDate = new DateTime(2029, 4, 28, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(1023),
                            LowStockThreshold = 0,
                            Name = "Baby Pacifiers 0-6 Months",
                            Quantity = 140
                        },
                        new
                        {
                            Id = 41,
                            Barcode = "849854112345",
                            Category = "Feeding",
                            DateAdded = new DateTime(2026, 3, 17, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(1026),
                            Description = "Silicone, easy clean, 3-pack",
                            LowStockThreshold = 0,
                            Name = "Baby Bibs - Waterproof",
                            Quantity = 92
                        },
                        new
                        {
                            Id = 42,
                            Barcode = "051000138262",
                            Category = "Baby Food",
                            DateAdded = new DateTime(2026, 3, 4, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(1029),
                            Description = "Organic stage 1, 4 oz jar",
                            ExpirationDate = new DateTime(2026, 6, 12, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(1028),
                            LowStockThreshold = 0,
                            Name = "Baby Food - Sweet Potatoes",
                            Quantity = 185
                        },
                        new
                        {
                            Id = 43,
                            Barcode = "051000138279",
                            Category = "Baby Food",
                            DateAdded = new DateTime(2026, 3, 11, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(1032),
                            Description = "Organic stage 1, 4 oz jar",
                            ExpirationDate = new DateTime(2026, 6, 17, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(1031),
                            LowStockThreshold = 0,
                            Name = "Baby Food - Carrots",
                            Quantity = 167
                        },
                        new
                        {
                            Id = 44,
                            Barcode = "849854123456",
                            Category = "Feeding",
                            DateAdded = new DateTime(2026, 3, 21, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(1034),
                            Description = "Soft-tip silicone, 6-pack",
                            LowStockThreshold = 0,
                            Name = "Baby Spoons",
                            Quantity = 78
                        },
                        new
                        {
                            Id = 45,
                            Barcode = "849854134567",
                            Category = "Feeding",
                            DateAdded = new DateTime(2026, 3, 7, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(1036),
                            Description = "BPA-free, 3-pack with lids",
                            LowStockThreshold = 0,
                            Name = "Baby Bowls with Suction",
                            Quantity = 61
                        },
                        new
                        {
                            Id = 46,
                            Barcode = "849854145678",
                            Category = "Baby Health",
                            DateAdded = new DateTime(2026, 3, 15, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(1038),
                            Description = "BPA-free silicone, 4-pack",
                            LowStockThreshold = 0,
                            Name = "Teething Toys",
                            Quantity = 103
                        },
                        new
                        {
                            Id = 47,
                            Barcode = "738443002151",
                            Category = "Baby Care",
                            DateAdded = new DateTime(2026, 2, 22, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(1041),
                            Description = "Mineral-based, tear-free, 3 oz",
                            ExpirationDate = new DateTime(2027, 8, 28, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(1040),
                            LowStockThreshold = 0,
                            Name = "Baby Sunscreen SPF 50",
                            Quantity = 47
                        },
                        new
                        {
                            Id = 48,
                            Barcode = "037000120261",
                            Category = "Baby Care",
                            DateAdded = new DateTime(2026, 2, 16, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(1042),
                            Description = "Dreft, hypoallergenic, 50 oz",
                            LowStockThreshold = 0,
                            Name = "Baby Laundry Detergent",
                            Quantity = 82
                        },
                        new
                        {
                            Id = 49,
                            Barcode = "849854156789",
                            Category = "Safety",
                            DateAdded = new DateTime(2026, 1, 30, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(1044),
                            Description = "Pressure-mounted, 29-38 inches",
                            LowStockThreshold = 0,
                            Name = "Baby Safety Gates",
                            Quantity = 18
                        },
                        new
                        {
                            Id = 50,
                            Barcode = "849854167890",
                            Category = "Safety",
                            DateAdded = new DateTime(2026, 2, 10, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(1054),
                            Description = "Child-proof, 36-pack",
                            LowStockThreshold = 0,
                            Name = "Outlet Covers",
                            Quantity = 234
                        },
                        new
                        {
                            Id = 51,
                            Barcode = "849854178901",
                            Category = "Safety",
                            DateAdded = new DateTime(2026, 1, 23, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(1056),
                            Description = "Video monitor with night vision",
                            LowStockThreshold = 0,
                            Name = "Baby Monitor",
                            Quantity = 12
                        },
                        new
                        {
                            Id = 52,
                            Barcode = "849854189012",
                            Category = "Baby Health",
                            DateAdded = new DateTime(2026, 1, 16, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(1058),
                            Description = "Cool mist, 1 gallon capacity",
                            LowStockThreshold = 0,
                            Name = "Baby Humidifier",
                            Quantity = 28
                        },
                        new
                        {
                            Id = 53,
                            Barcode = "849854190123",
                            Category = "Feeding",
                            DateAdded = new DateTime(2026, 3, 1, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(1059),
                            Description = "Disposable, 60 count box",
                            LowStockThreshold = 0,
                            Name = "Nursing Pads",
                            Quantity = 144
                        },
                        new
                        {
                            Id = 54,
                            Barcode = "849854201234",
                            Category = "Bathing",
                            DateAdded = new DateTime(2026, 2, 4, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(1061),
                            Description = "Infant to toddler, with sling",
                            LowStockThreshold = 0,
                            Name = "Baby Bath Tub",
                            Quantity = 22
                        },
                        new
                        {
                            Id = 55,
                            Barcode = "849854212345",
                            Category = "Baby Care",
                            DateAdded = new DateTime(2026, 2, 18, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(1063),
                            Description = "Soft bristle brush and comb",
                            LowStockThreshold = 0,
                            Name = "Baby Hair Brush Set",
                            Quantity = 67
                        },
                        new
                        {
                            Id = 56,
                            Barcode = "849854223456",
                            Category = "Diapering",
                            DateAdded = new DateTime(2026, 3, 13, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(1065),
                            Description = "Deodorizing, 6-pack rings",
                            LowStockThreshold = 0,
                            Name = "Diaper Pail Refills",
                            Quantity = 98
                        },
                        new
                        {
                            Id = 57,
                            Barcode = "849854234567",
                            Category = "Accessories",
                            DateAdded = new DateTime(2026, 1, 8, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(1067),
                            Description = "Ergonomic, 8-33 lbs capacity",
                            LowStockThreshold = 0,
                            Name = "Baby Carrier",
                            Quantity = 15
                        },
                        new
                        {
                            Id = 58,
                            Barcode = "849854245678",
                            Category = "Accessories",
                            DateAdded = new DateTime(2026, 1, 20, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(1068),
                            Description = "Universal fit, clear PVC",
                            LowStockThreshold = 0,
                            Name = "Stroller Rain Cover",
                            Quantity = 31
                        },
                        new
                        {
                            Id = 59,
                            Barcode = "849854256789",
                            Category = "Accessories",
                            DateAdded = new DateTime(2026, 2, 25, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(1070),
                            Description = "Velvet non-slip, 30-pack",
                            LowStockThreshold = 0,
                            Name = "Baby Hangers",
                            Quantity = 176
                        },
                        new
                        {
                            Id = 60,
                            Barcode = "363824012001",
                            Category = "Baby Health",
                            DateAdded = new DateTime(2026, 2, 12, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(1073),
                            Description = "Natural, benzocaine-free, 0.33 oz",
                            ExpirationDate = new DateTime(2026, 4, 30, 16, 41, 52, 307, DateTimeKind.Local).AddTicks(1072),
                            LowStockThreshold = 0,
                            Name = "Teething Gel",
                            Quantity = 54
                        });
                });

            modelBuilder.Entity("SafeFutureInventorySystem.Models.DonationLog", b =>
                {
                    b.HasOne("SafeFutureInventorySystem.Models.InventoryItem", "InventoryItem")
                        .WithMany("DonationLogs")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("SafeFutureInventorySystem.Models.InventoryAdjustmentLog", b =>
                {
                    b.HasOne("SafeFutureInventorySystem.Models.InventoryItem", null)
                        .WithMany("AdjustmentLogs")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SafeFutureInventorySystem.Models.InventoryItem", b =>
                {
                    b.Navigation("AdjustmentLogs");

                    b.Navigation("DonationLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
