// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SafeFutureInventorySystem.Data;

#nullable disable

namespace SafeFutureInventorySystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260120140622_AddQrCodeTable")]
    partial class AddQrCodeTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("SafeFutureInventorySystem.Models.InventoryAdjustmentLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdjustedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AdjustmentDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OldQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.ToTable("AdjustmentLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdjustedBy = "Admin",
                            AdjustmentDate = new DateTime(2026, 1, 15, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(8321),
                            InventoryItemId = 10,
                            NewQuantity = 150,
                            OldQuantity = 120,
                            Reason = "New shipment received"
                        },
                        new
                        {
                            Id = 2,
                            AdjustedBy = "Volunteer",
                            AdjustmentDate = new DateTime(2026, 1, 18, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(8523),
                            InventoryItemId = 10,
                            NewQuantity = 130,
                            OldQuantity = 150,
                            Reason = "Distributed to families"
                        },
                        new
                        {
                            Id = 3,
                            AdjustedBy = "Admin",
                            AdjustmentDate = new DateTime(2026, 1, 17, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(8526),
                            InventoryItemId = 18,
                            NewQuantity = 220,
                            OldQuantity = 250,
                            Reason = "Used for community event"
                        });
                });

            modelBuilder.Entity("SafeFutureInventorySystem.Models.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DonorEmail")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DonorName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DonorPhone")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("InventoryItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "070074680002",
                            Category = "Baby Formula",
                            DateAdded = new DateTime(2025, 9, 22, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(3644),
                            Description = "EXPIRED - Similac Advance, 12.4 oz",
                            DonorEmail = "sarah.j@email.com",
                            DonorName = "Sarah Johnson",
                            DonorPhone = "555-0101",
                            ExpirationDate = new DateTime(2025, 12, 21, 9, 6, 22, 270, DateTimeKind.Local).AddTicks(9486),
                            Name = "Expired Baby Formula",
                            Quantity = 15
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "036000516517",
                            Category = "Baby Wipes",
                            DateAdded = new DateTime(2025, 10, 22, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4261),
                            Description = "EXPIRED - Huggies Natural Care, 72 count",
                            DonorEmail = "m.chen@email.com",
                            DonorName = "Michael Chen",
                            DonorPhone = "555-0102",
                            ExpirationDate = new DateTime(2026, 1, 5, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4257),
                            Name = "Expired Baby Wipes",
                            Quantity = 8
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "085898800015",
                            Category = "Baby Care",
                            DateAdded = new DateTime(2025, 8, 23, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4267),
                            Description = "EXPIRED - Boudreaux's Butt Paste, 4 oz",
                            DonorName = "Jennifer Martinez",
                            DonorPhone = "555-0103",
                            ExpirationDate = new DateTime(2025, 11, 21, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4265),
                            Name = "Expired Diaper Cream",
                            Quantity = 3
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "050000339877",
                            Category = "Baby Formula",
                            DateAdded = new DateTime(2025, 11, 21, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4271),
                            Description = "EXPIRING SOON - Gentle powder, 32 oz",
                            DonorEmail = "r.williams@email.com",
                            DonorName = "Robert Williams",
                            ExpirationDate = new DateTime(2026, 1, 23, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4269),
                            Name = "Gerber Good Start Formula",
                            Quantity = 45
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "859668006010",
                            Category = "Baby Wipes",
                            DateAdded = new DateTime(2025, 12, 11, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4292),
                            Description = "EXPIRING SOON - 99.9% water, 540 count",
                            DonorEmail = "lisa.a@email.com",
                            DonorName = "Lisa Anderson",
                            DonorPhone = "555-0105",
                            ExpirationDate = new DateTime(2026, 1, 25, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4290),
                            Name = "WaterWipes Baby Wipes",
                            Quantity = 180
                        },
                        new
                        {
                            Id = 6,
                            Barcode = "051000138255",
                            Category = "Baby Food",
                            DateAdded = new DateTime(2025, 12, 1, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4295),
                            Description = "EXPIRING SOON - Stage 1, 4 oz jar",
                            DonorName = "Target Store #1234",
                            ExpirationDate = new DateTime(2026, 1, 27, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4294),
                            Name = "Organic Baby Food - Peas",
                            Quantity = 22
                        },
                        new
                        {
                            Id = 7,
                            Barcode = "070074682532",
                            Category = "Baby Formula",
                            DateAdded = new DateTime(2025, 12, 16, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4298),
                            Description = "Expiring this month - 30.8 oz powder",
                            DonorName = "David Thompson",
                            DonorPhone = "555-0107",
                            ExpirationDate = new DateTime(2026, 2, 14, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4297),
                            Name = "Similac Pro-Advance Formula",
                            Quantity = 130
                        },
                        new
                        {
                            Id = 8,
                            Barcode = "037000830689",
                            Category = "Baby Wipes",
                            DateAdded = new DateTime(2026, 1, 2, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4301),
                            Description = "Expiring this month - 504 count",
                            DonorEmail = "emily.d@email.com",
                            DonorName = "Emily Davis",
                            DonorPhone = "555-0108",
                            ExpirationDate = new DateTime(2026, 2, 9, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4300),
                            Name = "Pampers Sensitive Wipes",
                            Quantity = 250
                        },
                        new
                        {
                            Id = 9,
                            Barcode = "363824009001",
                            Category = "Baby Health",
                            DateAdded = new DateTime(2025, 12, 6, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4304),
                            Description = "Expiring this month - Liquid supplement",
                            DonorEmail = "j.wilson@email.com",
                            DonorName = "James Wilson",
                            ExpirationDate = new DateTime(2026, 2, 17, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4303),
                            Name = "Baby Vitamin D Drops",
                            Quantity = 68
                        },
                        new
                        {
                            Id = 10,
                            Barcode = "037000465911",
                            Category = "Diapers",
                            DateAdded = new DateTime(2025, 12, 21, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4322),
                            Description = "Size N, Up to 10 lbs, 32 count pack",
                            DonorEmail = "patricia.m@email.com",
                            DonorName = "Patricia Moore",
                            DonorPhone = "555-0110",
                            ExpirationDate = new DateTime(2027, 7, 20, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4305),
                            Name = "Pampers Newborn Diapers",
                            Quantity = 150
                        },
                        new
                        {
                            Id = 11,
                            Barcode = "036000406481",
                            Category = "Diapers",
                            DateAdded = new DateTime(2025, 12, 26, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4326),
                            Description = "Size 1, 8-14 lbs, 84 count pack",
                            DonorName = "Walmart Store #5678",
                            DonorPhone = "555-0111",
                            ExpirationDate = new DateTime(2028, 1, 20, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4324),
                            Name = "Huggies Size 1 Diapers",
                            Quantity = 200
                        },
                        new
                        {
                            Id = 12,
                            Barcode = "037000465928",
                            Category = "Diapers",
                            DateAdded = new DateTime(2025, 12, 31, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4329),
                            Description = "Size 2, 12-18 lbs, 112 count pack",
                            DonorEmail = "chris.t@email.com",
                            DonorName = "Christopher Taylor",
                            ExpirationDate = new DateTime(2027, 9, 20, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4328),
                            Name = "Pampers Size 2 Diapers",
                            Quantity = 180
                        },
                        new
                        {
                            Id = 13,
                            Barcode = "036000406498",
                            Category = "Diapers",
                            DateAdded = new DateTime(2026, 1, 5, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4340),
                            Description = "Size 3, 16-28 lbs, 104 count pack",
                            DonorEmail = "jessica.b@email.com",
                            DonorName = "Jessica Brown",
                            DonorPhone = "555-0113",
                            ExpirationDate = new DateTime(2027, 11, 20, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4331),
                            Name = "Huggies Size 3 Diapers",
                            Quantity = 165
                        },
                        new
                        {
                            Id = 14,
                            Barcode = "037000465935",
                            Category = "Diapers",
                            DateAdded = new DateTime(2026, 1, 10, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4343),
                            Description = "Size 4, 22-37 lbs, 92 count pack",
                            DonorName = "Daniel Garcia",
                            DonorPhone = "555-0114",
                            ExpirationDate = new DateTime(2027, 8, 20, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4342),
                            Name = "Pampers Size 4 Diapers",
                            Quantity = 140
                        },
                        new
                        {
                            Id = 15,
                            Barcode = "036000406504",
                            Category = "Diapers",
                            DateAdded = new DateTime(2026, 1, 12, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4346),
                            Description = "Size 5, 27+ lbs, 80 count pack",
                            DonorName = "St. Mary's Church",
                            ExpirationDate = new DateTime(2027, 10, 20, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4345),
                            Name = "Huggies Size 5 Diapers",
                            Quantity = 120
                        },
                        new
                        {
                            Id = 16,
                            Barcode = "037000465942",
                            Category = "Diapers",
                            DateAdded = new DateTime(2026, 1, 15, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4348),
                            Description = "Size 6, 35+ lbs, 68 count pack",
                            DonorEmail = "matt.r@email.com",
                            DonorName = "Matthew Rodriguez",
                            DonorPhone = "555-0116",
                            ExpirationDate = new DateTime(2027, 12, 20, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4347),
                            Name = "Pampers Size 6 Diapers",
                            Quantity = 95
                        },
                        new
                        {
                            Id = 17,
                            Barcode = "300871214415",
                            Category = "Baby Formula",
                            DateAdded = new DateTime(2025, 12, 23, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4351),
                            Description = "Infant formula powder, 28.3 oz",
                            DonorEmail = "ashley.l@email.com",
                            DonorName = "Ashley Lewis",
                            ExpirationDate = new DateTime(2026, 11, 20, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4350),
                            Name = "Enfamil NeuroPro Formula",
                            Quantity = 145
                        },
                        new
                        {
                            Id = 18,
                            Barcode = "036000516500",
                            Category = "Baby Wipes",
                            DateAdded = new DateTime(2025, 12, 29, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4354),
                            Description = "Fragrance-free, 552 count (8 packs)",
                            DonorName = "Joshua Walker",
                            DonorPhone = "555-0118",
                            ExpirationDate = new DateTime(2027, 3, 20, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4353),
                            Name = "Huggies Natural Care Wipes",
                            Quantity = 220
                        },
                        new
                        {
                            Id = 19,
                            Barcode = "067981105001",
                            Category = "Diapering",
                            DateAdded = new DateTime(2026, 1, 6, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4357),
                            Description = "Desitin Maximum Strength, 4 oz tube",
                            DonorEmail = "amanda.h@email.com",
                            DonorName = "Amanda Hall",
                            DonorPhone = "555-0119",
                            ExpirationDate = new DateTime(2027, 7, 20, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4356),
                            Name = "Diaper Rash Cream",
                            Quantity = 85
                        },
                        new
                        {
                            Id = 20,
                            Barcode = "381371161423",
                            Category = "Baby Care",
                            DateAdded = new DateTime(2026, 1, 3, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4359),
                            Description = "Johnson's Head-to-Toe, 27.1 fl oz",
                            DonorName = "Community Health Center",
                            ExpirationDate = new DateTime(2028, 7, 20, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4358),
                            Name = "Baby Shampoo & Body Wash",
                            Quantity = 135
                        },
                        new
                        {
                            Id = 21,
                            Barcode = "072239311004",
                            Category = "Feeding",
                            DateAdded = new DateTime(2026, 1, 9, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4361),
                            Description = "Dr. Brown's Anti-Colic, 3-pack",
                            DonorName = "Ryan Allen",
                            DonorPhone = "555-0121",
                            Name = "Baby Bottles 8oz",
                            Quantity = 70
                        },
                        new
                        {
                            Id = 22,
                            Barcode = "072239314012",
                            Category = "Feeding",
                            DateAdded = new DateTime(2026, 1, 4, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4363),
                            Description = "Silicone, 6-pack, 0-3 months",
                            DonorEmail = "samantha.y@email.com",
                            DonorName = "Samantha Young",
                            Name = "Bottle Nipples - Slow Flow",
                            Quantity = 125
                        },
                        new
                        {
                            Id = 23,
                            Barcode = "849854012345",
                            Category = "Feeding",
                            DateAdded = new DateTime(2026, 1, 11, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4373),
                            Description = "100% cotton, 10-pack set",
                            DonorEmail = "brandon.k@email.com",
                            DonorName = "Brandon King",
                            DonorPhone = "555-0123",
                            Name = "Burp Cloths",
                            Quantity = 90
                        },
                        new
                        {
                            Id = 24,
                            Barcode = "078742317298",
                            Category = "Clothing",
                            DateAdded = new DateTime(2025, 12, 30, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4374),
                            Description = "Short sleeve, 5-pack, assorted colors",
                            DonorName = "Nicole Wright",
                            DonorPhone = "555-0124",
                            Name = "Onesies 0-3 Months",
                            Quantity = 160
                        },
                        new
                        {
                            Id = 25,
                            Barcode = "078742317305",
                            Category = "Clothing",
                            DateAdded = new DateTime(2026, 1, 7, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4376),
                            Description = "Footed sleepers, fleece, 3-pack",
                            DonorEmail = "justin.s@email.com",
                            DonorName = "Justin Scott",
                            Name = "Baby Sleepers 3-6 Months",
                            Quantity = 105
                        },
                        new
                        {
                            Id = 26,
                            Barcode = "849854023456",
                            Category = "Clothing",
                            DateAdded = new DateTime(2026, 1, 14, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4378),
                            Description = "Non-slip grip, 12-pack",
                            DonorEmail = "megan.g@email.com",
                            DonorName = "Megan Green",
                            DonorPhone = "555-0126",
                            Name = "Baby Socks 0-12 Months",
                            Quantity = 200
                        },
                        new
                        {
                            Id = 27,
                            Barcode = "849854034567",
                            Category = "Clothing",
                            DateAdded = new DateTime(2025, 12, 27, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4380),
                            Description = "Scratch-free mittens, 6-pack",
                            DonorName = "Tyler Adams",
                            DonorPhone = "555-0127",
                            Name = "Baby Mittens",
                            Quantity = 80
                        },
                        new
                        {
                            Id = 28,
                            Barcode = "735363012010",
                            Category = "Diapering",
                            DateAdded = new DateTime(2026, 1, 13, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4382),
                            Description = "Waterproof, 50 count pack",
                            DonorName = "Rachel Baker",
                            Name = "Disposable Changing Pads",
                            Quantity = 65
                        },
                        new
                        {
                            Id = 29,
                            Barcode = "849854045678",
                            Category = "Baby Care",
                            DateAdded = new DateTime(2026, 1, 16, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4383),
                            Description = "Safety nail care set with file",
                            DonorEmail = "kevin.n@email.com",
                            DonorName = "Kevin Nelson",
                            DonorPhone = "555-0129",
                            Name = "Baby Nail Clippers",
                            Quantity = 55
                        },
                        new
                        {
                            Id = 30,
                            Barcode = "853689006133",
                            Category = "Baby Health",
                            DateAdded = new DateTime(2025, 12, 24, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4385),
                            Description = "NoseFrida with 20 filters",
                            DonorEmail = "lauren.c@email.com",
                            DonorName = "Lauren Carter",
                            Name = "Nasal Aspirator",
                            Quantity = 45
                        },
                        new
                        {
                            Id = 31,
                            Barcode = "849854056789",
                            Category = "Bedding",
                            DateAdded = new DateTime(2025, 12, 25, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4387),
                            Description = "Muslin, 4-pack, 47x47 inches",
                            DonorName = "Jacob Mitchell",
                            DonorPhone = "555-0131",
                            Name = "Swaddle Blankets",
                            Quantity = 100
                        },
                        new
                        {
                            Id = 32,
                            Barcode = "849854067890",
                            Category = "Bedding",
                            DateAdded = new DateTime(2026, 1, 5, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4389),
                            Description = "Fitted, 100% cotton, 2-pack",
                            DonorEmail = "kim.p@email.com",
                            DonorName = "Kimberly Perez",
                            DonorPhone = "555-0132",
                            Name = "Crib Sheets",
                            Quantity = 75
                        },
                        new
                        {
                            Id = 33,
                            Barcode = "849854078901",
                            Category = "Bathing",
                            DateAdded = new DateTime(2026, 1, 8, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4391),
                            Description = "Extra soft, 30x30 inches, 3-pack",
                            DonorName = "Austin Roberts",
                            Name = "Baby Hooded Towels",
                            Quantity = 88
                        },
                        new
                        {
                            Id = 34,
                            Barcode = "849854089012",
                            Category = "Bathing",
                            DateAdded = new DateTime(2025, 12, 22, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4399),
                            Description = "Ultra-soft, 12-pack",
                            DonorEmail = "brittany.t@email.com",
                            DonorName = "Brittany Turner",
                            Name = "Baby Washcloths",
                            Quantity = 150
                        },
                        new
                        {
                            Id = 35,
                            Barcode = "849854090123",
                            Category = "Accessories",
                            DateAdded = new DateTime(2025, 12, 20, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4401),
                            Description = "Multi-pocket backpack style",
                            DonorName = "Costco Wholesale",
                            DonorPhone = "555-0135",
                            Name = "Diaper Bags",
                            Quantity = 35
                        },
                        new
                        {
                            Id = 36,
                            Barcode = "849854101234",
                            Category = "Baby Health",
                            DateAdded = new DateTime(2025, 12, 18, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4403),
                            Description = "Digital forehead & ear thermometer",
                            DonorEmail = "zach.p@email.com",
                            DonorName = "Zachary Phillips",
                            DonorPhone = "555-0136",
                            Name = "Baby Thermometer",
                            Quantity = 50
                        },
                        new
                        {
                            Id = 37,
                            Barcode = "732913441914",
                            Category = "Diapers",
                            DateAdded = new DateTime(2026, 1, 8, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4406),
                            Description = "Eco-friendly, Size 1, 8-14 lbs, 40 count",
                            DonorName = "Hannah Campbell",
                            ExpirationDate = new DateTime(2027, 4, 20, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4405),
                            Name = "Seventh Generation Size 1 Diapers",
                            Quantity = 75
                        },
                        new
                        {
                            Id = 38,
                            Barcode = "381371161416",
                            Category = "Baby Care",
                            DateAdded = new DateTime(2026, 1, 1, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4409),
                            Description = "Johnson's Baby Powder, cornstarch, 9 oz",
                            DonorName = "Nathan Parker",
                            DonorPhone = "555-0138",
                            ExpirationDate = new DateTime(2028, 1, 20, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4408),
                            Name = "Baby Powder",
                            Quantity = 110
                        },
                        new
                        {
                            Id = 39,
                            Barcode = "381371161430",
                            Category = "Baby Care",
                            DateAdded = new DateTime(2025, 12, 28, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4412),
                            Description = "Aveeno Baby Daily Moisture, 18 fl oz",
                            DonorEmail = "alexis.e@email.com",
                            DonorName = "Alexis Evans",
                            ExpirationDate = new DateTime(2028, 3, 20, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4411),
                            Name = "Baby Lotion",
                            Quantity = 115
                        },
                        new
                        {
                            Id = 40,
                            Barcode = "072239314029",
                            Category = "Comfort",
                            DateAdded = new DateTime(2026, 1, 12, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4415),
                            Description = "Orthodontic, BPA-free, 4-pack",
                            DonorEmail = "sam.e@email.com",
                            DonorName = "Samuel Edwards",
                            DonorPhone = "555-0140",
                            ExpirationDate = new DateTime(2029, 1, 20, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4414),
                            Name = "Baby Pacifiers 0-6 Months",
                            Quantity = 140
                        },
                        new
                        {
                            Id = 41,
                            Barcode = "849854112345",
                            Category = "Feeding",
                            DateAdded = new DateTime(2025, 12, 9, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4417),
                            Description = "Silicone, easy clean, 3-pack",
                            DonorName = "Grace Collins",
                            Name = "Baby Bibs - Waterproof",
                            Quantity = 92
                        },
                        new
                        {
                            Id = 42,
                            Barcode = "051000138262",
                            Category = "Baby Food",
                            DateAdded = new DateTime(2025, 11, 26, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4419),
                            Description = "Organic stage 1, 4 oz jar",
                            DonorName = "Benjamin Stewart",
                            DonorPhone = "555-0142",
                            ExpirationDate = new DateTime(2026, 3, 6, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4418),
                            Name = "Baby Food - Sweet Potatoes",
                            Quantity = 185
                        },
                        new
                        {
                            Id = 43,
                            Barcode = "051000138279",
                            Category = "Baby Food",
                            DateAdded = new DateTime(2025, 12, 3, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4422),
                            Description = "Organic stage 1, 4 oz jar",
                            DonorEmail = "victoria.s@email.com",
                            DonorName = "Victoria Sanchez",
                            ExpirationDate = new DateTime(2026, 3, 11, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4421),
                            Name = "Baby Food - Carrots",
                            Quantity = 167
                        },
                        new
                        {
                            Id = 44,
                            Barcode = "849854123456",
                            Category = "Feeding",
                            DateAdded = new DateTime(2025, 12, 13, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4431),
                            Description = "Soft-tip silicone, 6-pack",
                            DonorEmail = "alex.m@email.com",
                            DonorName = "Alexander Morris",
                            DonorPhone = "555-0144",
                            Name = "Baby Spoons",
                            Quantity = 78
                        },
                        new
                        {
                            Id = 45,
                            Barcode = "849854134567",
                            Category = "Feeding",
                            DateAdded = new DateTime(2025, 11, 29, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4441),
                            Description = "BPA-free, 3-pack with lids",
                            DonorName = "Sophia Rogers",
                            DonorPhone = "555-0145",
                            Name = "Baby Bowls with Suction",
                            Quantity = 61
                        },
                        new
                        {
                            Id = 46,
                            Barcode = "849854145678",
                            Category = "Baby Health",
                            DateAdded = new DateTime(2025, 12, 7, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4442),
                            Description = "BPA-free silicone, 4-pack",
                            DonorName = "Elijah Reed",
                            Name = "Teething Toys",
                            Quantity = 103
                        },
                        new
                        {
                            Id = 47,
                            Barcode = "738443002151",
                            Category = "Baby Care",
                            DateAdded = new DateTime(2025, 11, 16, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4445),
                            Description = "Mineral-based, tear-free, 3 oz",
                            DonorEmail = "olivia.c@email.com",
                            DonorName = "Olivia Cook",
                            DonorPhone = "555-0147",
                            ExpirationDate = new DateTime(2027, 5, 20, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4444),
                            Name = "Baby Sunscreen SPF 50",
                            Quantity = 47
                        },
                        new
                        {
                            Id = 48,
                            Barcode = "037000120261",
                            Category = "Baby Care",
                            DateAdded = new DateTime(2025, 11, 10, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4447),
                            Description = "Dreft, hypoallergenic, 50 oz",
                            DonorEmail = "mason.m@email.com",
                            DonorName = "Mason Morgan",
                            Name = "Baby Laundry Detergent",
                            Quantity = 82
                        },
                        new
                        {
                            Id = 49,
                            Barcode = "849854156789",
                            Category = "Safety",
                            DateAdded = new DateTime(2025, 10, 24, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4449),
                            Description = "Pressure-mounted, 29-38 inches",
                            DonorName = "Ava Bell",
                            DonorPhone = "555-0149",
                            Name = "Baby Safety Gates",
                            Quantity = 18
                        },
                        new
                        {
                            Id = 50,
                            Barcode = "849854167890",
                            Category = "Safety",
                            DateAdded = new DateTime(2025, 11, 4, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4450),
                            Description = "Child-proof, 36-pack",
                            DonorEmail = "lucas.m@email.com",
                            DonorName = "Lucas Murphy",
                            DonorPhone = "555-0150",
                            Name = "Outlet Covers",
                            Quantity = 234
                        },
                        new
                        {
                            Id = 51,
                            Barcode = "849854178901",
                            Category = "Safety",
                            DateAdded = new DateTime(2025, 10, 17, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4452),
                            Description = "Video monitor with night vision",
                            DonorName = "Isabella Bailey",
                            Name = "Baby Monitor",
                            Quantity = 12
                        },
                        new
                        {
                            Id = 52,
                            Barcode = "849854189012",
                            Category = "Baby Health",
                            DateAdded = new DateTime(2025, 10, 10, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4454),
                            Description = "Cool mist, 1 gallon capacity",
                            DonorName = "Ethan Rivera",
                            DonorPhone = "555-0152",
                            Name = "Baby Humidifier",
                            Quantity = 28
                        },
                        new
                        {
                            Id = 53,
                            Barcode = "849854190123",
                            Category = "Feeding",
                            DateAdded = new DateTime(2025, 11, 23, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4456),
                            Description = "Disposable, 60 count box",
                            DonorEmail = "mia.c@email.com",
                            DonorName = "Mia Cooper",
                            Name = "Nursing Pads",
                            Quantity = 144
                        },
                        new
                        {
                            Id = 54,
                            Barcode = "849854201234",
                            Category = "Bathing",
                            DateAdded = new DateTime(2025, 10, 29, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4458),
                            Description = "Infant to toddler, with sling",
                            DonorEmail = "logan.r@email.com",
                            DonorName = "Logan Richardson",
                            DonorPhone = "555-0154",
                            Name = "Baby Bath Tub",
                            Quantity = 22
                        },
                        new
                        {
                            Id = 55,
                            Barcode = "849854212345",
                            Category = "Baby Care",
                            DateAdded = new DateTime(2025, 11, 12, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4459),
                            Description = "Soft bristle brush and comb",
                            DonorName = "Charlotte Cox",
                            DonorPhone = "555-0155",
                            Name = "Baby Hair Brush Set",
                            Quantity = 67
                        },
                        new
                        {
                            Id = 56,
                            Barcode = "849854223456",
                            Category = "Diapering",
                            DateAdded = new DateTime(2025, 12, 5, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4462),
                            Description = "Deodorizing, 6-pack rings",
                            DonorName = "Aiden Howard",
                            Name = "Diaper Pail Refills",
                            Quantity = 98
                        },
                        new
                        {
                            Id = 57,
                            Barcode = "849854234567",
                            Category = "Accessories",
                            DateAdded = new DateTime(2025, 10, 2, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4464),
                            Description = "Ergonomic, 8-33 lbs capacity",
                            DonorEmail = "amelia.w@email.com",
                            DonorName = "Amelia Ward",
                            DonorPhone = "555-0157",
                            Name = "Baby Carrier",
                            Quantity = 15
                        },
                        new
                        {
                            Id = 58,
                            Barcode = "849854245678",
                            Category = "Accessories",
                            DateAdded = new DateTime(2025, 10, 14, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4465),
                            Description = "Universal fit, clear PVC",
                            DonorEmail = "liam.t@email.com",
                            DonorName = "Liam Torres",
                            Name = "Stroller Rain Cover",
                            Quantity = 31
                        },
                        new
                        {
                            Id = 59,
                            Barcode = "849854256789",
                            Category = "Accessories",
                            DateAdded = new DateTime(2025, 11, 19, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4467),
                            Description = "Velvet non-slip, 30-pack",
                            DonorName = "Harper Peterson",
                            DonorPhone = "555-0159",
                            Name = "Baby Hangers",
                            Quantity = 176
                        },
                        new
                        {
                            Id = 60,
                            Barcode = "363824012001",
                            Category = "Baby Health",
                            DateAdded = new DateTime(2025, 11, 6, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4470),
                            Description = "Natural, benzocaine-free, 0.33 oz",
                            DonorEmail = "noah.g@email.com",
                            DonorName = "Noah Gray",
                            DonorPhone = "555-0160",
                            ExpirationDate = new DateTime(2026, 1, 22, 9, 6, 22, 272, DateTimeKind.Local).AddTicks(4469),
                            Name = "Teething Gel",
                            Quantity = 54
                        });
                });

            modelBuilder.Entity("SafeFutureInventorySystem.Models.QrCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Format")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("QR_CODE");

                    b.Property<DateTime>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.ToTable("QrCodes");
                });

            modelBuilder.Entity("SafeFutureInventorySystem.Models.InventoryAdjustmentLog", b =>
                {
                    b.HasOne("SafeFutureInventorySystem.Models.InventoryItem", null)
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SafeFutureInventorySystem.Models.QrCode", b =>
                {
                    b.HasOne("SafeFutureInventorySystem.Models.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");
                });
#pragma warning restore 612, 618
        }
    }
}
